GET http://localhost:4000/todos
###

GET http://localhost:4000/todos/5
###

POST http://localhost:4000/todos
Content-Type: application/json

{
  "id": 1,
  "title": "Backup files"
}
###

PUT http://localhost:4000/todos/3
Content-Type: application/json

{
    "completed": 1
}
###

DELETE http://localhost:3000/todos/14